/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ComicbookDynamodbTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ComicbookHttpPrivateApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ComicbookHttpPublicApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ComicbookIdempotencyTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ComicbookPagesCleanUpIssuePageThumbnailQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesCleanUpIssuePageThumbnailQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesCleanUpIssuePagesQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesCleanUpIssuePagesQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesUpdateIssuePageThumbnailQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesUpdateIssuePageThumbnailQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesUpdateIssuePagesQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookPagesUpdateIssuePagesQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ComicbookS3Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ComicbookSecretsListIssuesBySeriesCursorSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ComicbookSecretsListPublishersCursorSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ComicbookSecretsListSeriesByPublisherCursorSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
